/** 后台权限码常量，必须与后端 @PreAuthorize 和 permission.permission_code 保持一致。 */
export const ADMIN_PERMISSIONS = {
  /** 智能助手入口权限。 */
  smartAssistant: {
    access: 'system:smart_assistant',
  },
  analytics: {
    query: 'mall:analytics:query',
  },
  mallProduct: {
    menu: 'mall:product',
    list: 'mall:product:list',
    query: 'mall:product:query',
    add: 'mall:product:add',
    edit: 'mall:product:edit',
    delete: 'mall:product:delete',
  },
  mallCategory: {
    menu: 'mall:category',
    tree: 'mall:category:tree',
    option: 'mall:category:option',
    query: 'mall:category:query',
    add: 'mall:category:add',
    edit: 'mall:category:edit',
    delete: 'mall:category:delete',
  },
  mallOrder: {
    menu: 'mall:order',
    list: 'mall:order:list',
    query: 'mall:order:query',
    edit: 'mall:order:edit',
    ship: 'mall:order:ship',
    cancel: 'mall:order:cancel',
    refund: 'mall:order:refund',
    delete: 'mall:order:delete',
  },
  mallAfterSale: {
    menu: 'mall:after_sale',
    list: 'mall:after_sale:list',
    query: 'mall:after_sale:query',
    audit: 'mall:after_sale:audit',
    refund: 'mall:after_sale:refund',
    exchange: 'mall:after_sale:exchange',
  },
  mallProductTag: {
    menu: 'mall:product:tag',
    list: 'mall:product:tag:list',
    query: 'mall:product:tag:query',
    add: 'mall:product:tag:add',
    edit: 'mall:product:tag:edit',
    delete: 'mall:product:tag:delete',
  },
  mallCoupon: {
    menu: 'mall:coupon',
    template: 'mall:coupon:template',
    templateList: 'mall:coupon:template:list',
    templateQuery: 'mall:coupon:template:query',
    templateAdd: 'mall:coupon:template:add',
    templateEdit: 'mall:coupon:template:edit',
    templateDelete: 'mall:coupon:template:delete',
    issue: 'mall:coupon:issue',
    activationBatch: 'mall:coupon:activation-batch',
    activationBatchGenerate: 'mall:coupon:activation-batch:generate',
    activationBatchList: 'mall:coupon:activation-batch:list',
    activationBatchQuery: 'mall:coupon:activation-batch:query',
    activationBatchStatus: 'mall:coupon:activation-batch:status',
    log: 'mall:coupon:log',
    logList: 'mall:coupon:log:list',
    activationLog: 'mall:coupon:activation-log',
    activationLogList: 'mall:coupon:activation-log:list',
  },
  systemUser: {
    menu: 'system:user',
    list: 'system:user:list',
    query: 'system:user:query',
    add: 'system:user:add',
    update: 'system:user:update',
    delete: 'system:user:delete',
  },
  systemRole: {
    menu: 'system:role',
    list: 'system:role:list',
    query: 'system:role:query',
    add: 'system:role:add',
    update: 'system:role:update',
    delete: 'system:role:delete',
  },
  systemPermission: {
    menu: 'system:permission',
    list: 'system:permission:list',
    query: 'system:permission:query',
    add: 'system:permission:add',
    update: 'system:permission:update',
    delete: 'system:permission:delete',
  },
  systemConfig: {
    menu: 'system:config',
    securityQuery: 'system:security_config:query',
    securityUpdate: 'system:security_config:update',
    agreementQuery: 'system:agreement_config:query',
    agreementUpdate: 'system:agreement_config:update',
    esIndexQuery: 'system:es_index:query',
    esIndexRebuild: 'system:es_index:rebuild',
  },
  systemLog: {
    operationList: 'system:operation-log:list',
    operationQuery: 'system:operation-log:query',
    operationDelete: 'system:operation-log:delete',
    loginList: 'system:login_log:list',
    loginQuery: 'system:login_log:query',
    loginDelete: 'system:login_log:delete',
  },
  knowledgeBase: {
    menu: 'system:knowledge_base',
    list: 'system:knowledge_base:list',
    query: 'system:knowledge_base:query',
    add: 'system:knowledge_base:add',
    update: 'system:knowledge_base:update',
    delete: 'system:knowledge_base:delete',
  },
  kbDocument: {
    menu: 'system:kb_document',
    list: 'system:kb_document:list',
    query: 'system:kb_document:query',
    update: 'system:kb_document:update',
    delete: 'system:kb_document:delete',
    import: 'system:kb_document:import',
  },
  kbDocumentChunk: {
    menu: 'system:kb_document_chunk',
    list: 'system:kb_document_chunk:list',
    add: 'system:kb_document_chunk:add',
    update: 'system:kb_document_chunk:update',
    delete: 'system:kb_document_chunk:delete',
  },
  llmProvider: {
    menu: 'system:llm_provider',
    list: 'system:llm_provider:list',
    query: 'system:llm_provider:query',
    add: 'system:llm_provider:add',
    test: 'system:llm_provider:test',
    update: 'system:llm_provider:update',
    delete: 'system:llm_provider:delete',
  },
  llmProviderModel: {
    menu: 'system:llm_provider_model',
    list: 'system:llm_provider_model:list',
    add: 'system:llm_provider_model:add',
    update: 'system:llm_provider_model:update',
    delete: 'system:llm_provider_model:delete',
  },
  agentConfig: {
    menu: 'system:agent_config',
    adminQuery: 'system:agent_config:admin:query',
    adminUpdate: 'system:agent_config:admin:update',
    clientQuery: 'system:agent_config:client:query',
    clientUpdate: 'system:agent_config:client:update',
    commonQuery: 'system:agent_config:common:query',
    commonUpdate: 'system:agent_config:common:update',
  },
  agentPrompt: {
    menu: 'system:agent_prompt',
    list: 'system:agent_prompt:list',
    query: 'system:agent_prompt:query',
    update: 'system:agent_prompt:update',
    rollback: 'system:agent_prompt:rollback',
    sync: 'system:agent_prompt:sync',
    delete: 'system:agent_prompt:delete',
  },
} as const;

/** 优惠券二级菜单入口权限集合。 */
export const COUPON_ROUTE_PERMISSIONS = [
  ADMIN_PERMISSIONS.mallCoupon.templateList,
  ADMIN_PERMISSIONS.mallCoupon.activationBatchList,
  ADMIN_PERMISSIONS.mallCoupon.logList,
  ADMIN_PERMISSIONS.mallCoupon.activationLogList,
];

/** 系统配置二级菜单入口权限集合。 */
export const SYSTEM_CONFIG_ROUTE_PERMISSIONS = [
  ADMIN_PERMISSIONS.systemConfig.securityQuery,
  ADMIN_PERMISSIONS.systemConfig.agreementQuery,
  ADMIN_PERMISSIONS.systemConfig.esIndexQuery,
];

/** 系统模型配置二级菜单入口权限集合。 */
export const LLM_SYSTEM_MODELS_ROUTE_PERMISSIONS = [
  ADMIN_PERMISSIONS.agentConfig.adminQuery,
  ADMIN_PERMISSIONS.agentConfig.clientQuery,
  ADMIN_PERMISSIONS.agentConfig.commonQuery,
];
