import { Empty, Modal, message, Tree } from 'antd';
import React, { useEffect, useState } from 'react';
import { getRolePermission, updateRolePermission } from '@/api/system/role';
import type { Option } from '@/types';

export type PermissionAssignFormProps = {
  open: boolean;
  onOpenChange: (visible: boolean) => void;
  onFinish: () => void;
  roleId?: string;
};

const PermissionAssignForm: React.FC<PermissionAssignFormProps> = (props) => {
  const { open, onOpenChange, onFinish, roleId } = props;
  const [treeData, setTreeData] = useState<Option<string | number>[]>([]);
  const [checkedKeys, setCheckedKeys] = useState<(string | number)[]>([]);
  const [halfCheckedKeys, setHalfCheckedKeys] = useState<(string | number)[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [confirmLoading, setConfirmLoading] = useState<boolean>(false);

  useEffect(() => {
    if (open && roleId) {
      fetchRolePermission();
    }
  }, [open, roleId]);

  const fetchRolePermission = async () => {
    setLoading(true);
    try {
      const data = await getRolePermission(roleId!);
      const options = data.permissionOption || [];
      setTreeData(options);

      // Filter out parent keys from the backend response to prevent auto-selecting all children
      const parentKeys = new Set<string | number>();
      const traverse = (nodes: Option<string | number>[]) => {
        nodes.forEach((node) => {
          if (node.children && node.children.length > 0) {
            parentKeys.add(node.value!);
            traverse(node.children);
          }
        });
      };
      traverse(options);

      const allChecked = data.rolePermission || [];
      const leafChecked = allChecked.filter((key) => !parentKeys.has(key));
      setCheckedKeys(leafChecked);

      // We technically lose the "half-checked" state from backend if not provided explicitly,
      // but Antd Tree will re-calculate half-checked state based on leaf nodes.
      // So we don't need to manually set halfCheckedKeys on initial load,
      // they will be generated by the Tree component's internal logic upon first render/check?
      // Wait, Antd Tree in uncontrolled mode handles calculations. In controlled mode (checkedKeys provided),
      // we might need to be careful. But usually providing leaves is enough for it to figure out parents visually.
    } catch (error) {
      console.error(error);
      message.error('获取权限失败，请重试');
    } finally {
      setLoading(false);
    }
  };

  const handleOk = async () => {
    if (!roleId) return;
    setConfirmLoading(true);
    try {
      // Include both checked and half-checked keys
      const finalIds = [...checkedKeys, ...halfCheckedKeys];

      await updateRolePermission({
        roleId,
        permissionIds: finalIds.map(String),
      });

      message.success('权限分配成功');
      onFinish();
      onOpenChange(false);
    } catch (error) {
      console.error(error);
    } finally {
      setConfirmLoading(false);
    }
  };

  const onCheck = (checkedKeysValue: any, info: any) => {
    setCheckedKeys(checkedKeysValue);
    setHalfCheckedKeys(info.halfCheckedKeys || []);
  };

  const mapTreeData = (data: Option<string | number>[]): any[] => {
    return data.map((item) => ({
      title: item.label,
      key: item.value,
      children: item.children ? mapTreeData(item.children) : undefined,
    }));
  };

  return (
    <Modal
      title="分配权限"
      open={open}
      onOk={handleOk}
      onCancel={() => onOpenChange(false)}
      confirmLoading={confirmLoading}
      loading={loading}
      width={600}
      destroyOnHidden
    >
      {treeData.length > 0 ? (
        <Tree
          checkable
          checkedKeys={checkedKeys}
          onCheck={onCheck}
          treeData={mapTreeData(treeData)}
          defaultExpandAll
          height={500}
        />
      ) : (
        <Empty description="暂无可分配的权限数据" />
      )}
    </Modal>
  );
};

export default PermissionAssignForm;
